# Generated by Django 4.2.3 on 2023-12-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internos', '0002_rename_telefono_interno_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interno',
            name='servicio',
            field=models.CharField(max_length=80),
        ),
    ]
