# Generated by Django 4.2.3 on 2024-02-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(blank=True, choices=[('Normativa General', 'Normativa General'), ('Protocolos de Control de Infecciones', 'Protocolos de Control de Infecciones'), ('Protocolos Generales', 'Protocolos Generales'), ('Protocolos de Servicios', 'Protocolos de Servicios'), ('Instructivo de procedimientos', 'Instructivo de procedimientos')], max_length=50, null=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('archivo_pdf', models.FileField(upload_to='pdf/')),
                ('archivo_word', models.FileField(upload_to='word/')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_implementacion', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='protocolos.documento')),
            ],
        ),
    ]
