# Generated by Django 4.2.3 on 2023-08-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('Agente', models.CharField(max_length=80)),
                ('servicio', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=80)),
            ],
        ),
    ]
