# Generated by Django 4.2.3 on 2023-08-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Agente',
            new_name='agente',
        ),
    ]
