# Generated by Django 4.2.3 on 2023-08-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculos', '0002_rename_agente_vehiculo_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='telefono',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
