# Generated by Django 4.2.3 on 2023-08-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculos', '0003_alter_vehiculo_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='agente',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='servicio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
