# Generated by Django 4.2.3 on 2024-02-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('servicio', models.CharField(blank=True, choices=[('Clinica Medica', 'Clinica Medica'), ('Guardia Adultos', 'Guardia de Adultos'), ('Maternidad', 'Maternidad'), ('Neo', 'Neo'), ('Partos', 'Partos'), ('Pediatria Guardia', 'Pedriatria Guardia'), ('Pediatria Internacion', 'Pediatria Internacion'), ('Polivalente', 'Polivalente'), ('Quirofano', 'Quirofano'), ('UCI', 'UCI'), ('UTI', 'UTI'), ('Coordinacion', 'Coordinacion'), ('Casa de Madres', 'Casa de Madres')], default='-', max_length=50)),
                ('habitacion', models.CharField(max_length=80)),
                ('cama', models.CharField(blank=True, max_length=80, null=True)),
                ('diagnostico', models.TextField(default='Sin diagnóstico', max_length=80)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Internado', 'Continúa internado'), ('Dado de alta', 'Dado de alta'), ('Se fue sin alta médica', 'Se fue sin alta médica'), ('Derivado', 'Fue derivado'), ('Óbito', 'Óbito')], default='Internado', max_length=50)),
                ('anotaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
