# Generated by Django 4.2.1 on 2023-07-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_2023', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='servicio',
            field=models.CharField(choices=[('Clinica Medica', 'Clinica Medica'), ('Guardia Adultos', 'Guarda de Adultos'), ('Neo', 'Neo'), ('Pediatria Guardia', 'Pedriatria Guardia'), ('Pediatria Internacion', 'Pediatria Internacion'), ('Polivalente', 'Polivalente'), ('UCI    ', 'UCI    '), ('UTI    ', 'UTI    ')], max_length=50),
        ),
    ]
