# Generated by Django 4.2.1 on 2023-07-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_2023', '0002_alter_paciente_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='servicio',
            field=models.CharField(choices=[('Clinica Medica', 'Clinica Medica'), ('Guardia Adultos', 'Guarda de Adultos'), ('Maternidad', 'Maternidad'), ('Neo', 'Neo'), ('Partos', 'Partos'), ('Pediatria Guardia', 'Pedriatria Guardia'), ('Pediatria Internacion', 'Pediatria Internacion'), ('Polivalente', 'Polivalente'), ('UCI    ', 'UCI    '), ('UTI    ', 'UTI    ')], max_length=50),
        ),
    ]
