# Generated by Django 4.2.3 on 2023-08-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_2023', '0003_alter_paciente_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.TextField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='servicio',
            field=models.CharField(choices=[('Clinica Medica', 'Clinica Medica'), ('Guardia Adultos', 'Guardia de Adultos'), ('Maternidad', 'Maternidad'), ('Neo', 'Neo'), ('Partos', 'Partos'), ('Pediatria Guardia', 'Pedriatria Guardia'), ('Pediatria Internacion', 'Pediatria Internacion'), ('Polivalente', 'Polivalente'), ('Quirofano', 'Quirofano'), ('UCI', 'UCI'), ('UTI', 'UTI'), ('Coordinacion', 'Coordinacion'), ('Casa de Madres', 'Casa de Madres')], max_length=50),
        ),
    ]
