# Generated by Django 4.2.3 on 2023-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_2023', '0004_paciente_diagnostico_alter_paciente_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico',
            field=models.TextField(default='Sin diagnóstico', max_length=80),
        ),
    ]
