# Generated by Django 4.2.3 on 2023-11-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_2023', '0005_alter_paciente_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
