# Generated by Django 4.2.3 on 2023-11-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_2023', '0006_paciente_fecha_egreso_paciente_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='anotaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('Internado', 'Continúa internado'), ('Dado de alta', 'Dado de alta'), ('Se fue sin alta médica', 'Se fue sin alta médica'), ('Derivado', 'Fue derivado'), ('Óbito', 'Óbito')], default='Internado', max_length=50),
        ),
    ]
