# Generated by Django 4.2.3 on 2023-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_2023', '0009_alter_paciente_cama_alter_paciente_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='habitacion',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
